const pohina = [
    "Agile/scrum",
    "Pivotointi",
    "Kryptovaluutta",
    "Skaalautuvuus",
    "Synergia",
    "Käyttäjä\xADlähtöinen sisältö",
    "Orgaaninen",
    "Crowdsourcing",
    "Optimoitu",
    "Growth hacking",
    "Big data",
    "Wireframe",
    "Disruptoida",
    "Deprekoida",
    "Diversiteetti",
    "Alusta",
    "Optionaalisuus",
    "Bootstrappaus",
    "Synergistisyys",
    "Ideaatio",
    "Ekosysteemi",
    "Iteraatio",
    "Alustatalous"
]

const normal = [
    "Nauris",
    "Urho Kekkonen",
    "Maatalous",
    "Hylkeenpoikanen",
    "Villapaita",
    "Äreä",
    "Öljyväri",
    "Rakkaus",
    "Sirkusteltta",
    "Jäätelö",
    "Karaokeisäntä",
    "Laiton",
    "Pokémon",
    "Nakkilan kunta",
    "Perseensuti",
    "Drinkkilista",
    "Luostari",
    "Aineeton",
    "Vuohi",
]

export {pohina, normal}