const hustlelist = [
    "nagile/scrum",
    "pivotointi",
    "kryptovaluutta",
    "skaalautuvuus",
    "synergia",
    "käyttäjälähtöinen sisältö/UGC",
    "orgaaninen",
    "crowdsourcing",
    "optimoitu",
    "growth hacking",
    "big data",
    "wireframe",
    "disruptoida",
    "deprekoida",
    "diversiteetti",
    "alusta",
    "optionaalisuus",
    "bootstrappaus",
    "synergistisyys",
    "ideaatio",
    "ekosysteemi",
    "iteraatio",
]

const normallist = [
    "nauris",
    "Urho Kekkonen",
    "maatalous",
    "hylkeenpoikanen",
    "villapaita",
    "äreä",
    "öljyväri",
    "rakkaus",
    "sirkusteltta",
    "jäätelö",
    "karaokeisäntä",
    "laiton",
    "Pokémon",
    "Nakkilan kunta",
    "perseensuti",
    "drinkkilista",
    "luostari",
]

export {hustlelist, normallist}